# Generated by Django 5.1.1 on 2025-02-13 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fire, Medical, Security', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Firestation, Ambulance, Natural Disaster Team', max_length=255, unique=True)),
                ('team_type', models.CharField(help_text='Fire, Medical, Police', max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('dispatched', 'Dispatched'), ('on_seen', 'On Seen'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emergency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.emergencytype')),
                ('assigned_teams', models.ManyToManyField(blank=True, to='sos.responseteam')),
            ],
        ),
    ]
