# Generated by Django 5.1.1 on 2025-02-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.emergency')),
            ],
        ),
    ]
