# Generated by Django 5.1.1 on 2025-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_emergency_description_emergencycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmergencyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
