# Generated by Django 5.1.1 on 2025-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_personalemergencycontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Emergency Report', 'verbose_name_plural': 'Emergency Reports'},
        ),
        migrations.AddField(
            model_name='emergency',
            name='location',
            field=models.CharField(choices=[('location_1', 'Location 1'), ('location_2', 'Location 2'), ('location_3', 'Location 3'), ('location_4', 'Location 4'), ('location_5', 'Location 5')], default='location_1', help_text='Select the location of the emergency', max_length=20),
        ),
    ]
