# Generated by Django 5.1.1 on 2025-03-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_aidtip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontacts',
            name='emergency',
        ),
        migrations.AddField(
            model_name='emergencycontacts',
            name='emergency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sos.emergencytype'),
            preserve_default=False,
        ),
    ]
