# Generated by Django 5.1.1 on 2025-08-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_alter_emergency_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='assigned_teams',
        ),
        migrations.AddField(
            model_name='emergency',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='sos.responseteam'),
        ),
    ]
